# AE Pioneer - T1 engineer. Repairs + builds turrets/walls, light self-defense gun.
[core]
name: aeBeaver
class: CustomUnitMetadata
price: 450
maxHp: 180
mass: 1800
techLevel: 1
buildSpeed: 7s
radius: 9
displayRadius: 10
softCollisionOnAll: 4
isBuilder: true
availableInDemo: true

displayText: Beaver
displayDescription: -Repairs and builds defences\n-Light self-defense gun\n-Vulnerable alone

canRepairUnits: true
nanoRepairSpeed: 0.2
nanoRange: 75

canBuild_1_name: turret
canBuild_1_pos: 1
canBuild_2_name: wall_v
canBuild_2_pos: 2

builtFrom_1_name: landFactory
builtFrom_1_pos: 1.4
builtFrom_2_name: commandCenter
builtFrom_2_pos: 4

[graphics]
total_frames: 1
image: aeBeaver.png
image_wreak: aeBeaver_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 5
turretTurnSpeed: 5
maxAttackRange: 100
shootDelay: 0.6s

[turret_1]
x: 0
y: 0
projectile: 1
turnSpeed: 5
canShoot: true
shoot_sound: gun_fire
shoot_sound_vol: 0.08

[projectile_1]
directDamage: 7
life: 45
speed: 8
frame: 0
drawSize: 0.7

[movement]
movementType: LAND
moveSpeed: 0.95
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 4
turnAcceleration: 0.3

[ai]
useAsBuilder: false
