# AE Ranger - starter-base recon buggy. Fastest unit in the mod, huge sight, zero weapons.
[core]
name: aeGrasshopper
class: CustomUnitMetadata
price: 200
maxHp: 90
mass: 300
techLevel: 1
buildSpeed: 2s
radius: 7
displayRadius: 8
softCollisionOnAll: 3
availableInDemo: true

displayText: Grasshopper
displayDescription: -Very fast scout\n-Huge sight range\n-Unarmed

fogOfWarSightRange: 30

builtFrom_1_name: commandCenter
builtFrom_1_pos: 2

[graphics]
total_frames: 1
image: aeGrasshopper.png
image_wreak: aeGrasshopper_dead.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

[movement]
movementType: LAND
moveSpeed: 2.2
moveAccelerationSpeed: 0.12
moveDecelerationSpeed: 0.25
maxTurnSpeed: 7
turnAcceleration: 0.5

[ai]
useAsBuilder: false
