# Turtle - AE defense anchor
[core]
name: aeTurtle
class: CustomUnitMetadata
price: 3500
maxHp: 800
mass: 13100
techLevel: 3
buildSpeed: 7s
radius: 14
displayRadius: 14
isBio: false
availableInDemo: true
maxShield: 400
shieldRegen: 0.15
canRepairUnits: true
nanoRepairSpeed: 0.3
nanoRange: 85
displayText: Turtle
displayDescription: -defense anchor

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.9

[graphics]
total_frames: 1
image: aeTurtle.png
image_wreak: aeTurtle_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 11
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
