# Bedrock - AE super-heavy
[core]
name: aeBedrock
class: CustomUnitMetadata
price: 4200
maxHp: 2000
mass: 28200
techLevel: 3
buildSpeed: 8s
radius: 16
displayRadius: 16
isBio: false
availableInDemo: true
armour: 10
armourMinDamageToKeep: 5
displayText: Bedrock
displayDescription: -super-heavy

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.7

[graphics]
total_frames: 1
image: aeBedrock.png
image_wreak: aeBedrock_dead.png
image_turret: aeBedrock_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 13
turretTurnSpeed: 4
maxAttackRange: 190
shootDelay: 2.5s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 100
life: 70
speed: 6
frame: 4
drawSize: 1

[movement]
movementType: LAND
moveSpeed: 0.45
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
