# A2-08 Scrapper - AE armed salvager
[core]
name: ae_A2_08_Scrapper
class: CustomUnitMetadata
price: 700
maxHp: 190
mass: 2980
techLevel: 2
buildSpeed: 3s
radius: 10
displayRadius: 10
isBio: false
availableInDemo: true
nanoUnbuildSpeed: 1.5
nanoRange: 75
displayText: A2-08 Scrapper
displayDescription: -armed salvager

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.8

[canBuild_1]
name: reclaim
pos: -1

[graphics]
total_frames: 1
image: ae_A2_08_Scrapper.png
image_wreak: ae_A2_08_Scrapper_dead.png
image_turret: ae_A2_08_Scrapper_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 7
turretTurnSpeed: 4
maxAttackRange: 100
shootDelay: 0.5s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: gun_fire
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 8
life: 70
speed: 6
frame: 2
drawSize: 1

[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
