# S2-06 Owl - AE mobile radar
[core]
name: ae_S2_06_Owl
class: CustomUnitMetadata
price: 700
maxHp: 150
mass: 2500
techLevel: 2
buildSpeed: 3s
radius: 10
displayRadius: 10
isBio: false
availableInDemo: true
fogOfWarSightRange: 40
displayText: S2-06 Owl
displayDescription: -mobile radar

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.8

[graphics]
total_frames: 1
image: ae_S2_06_Owl.png
image_wreak: ae_S2_06_Owl_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 7
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
