# A3-02 Wick - AE flame walker
[core]
name: aeA3_02_Wick
class: CustomUnitMetadata
price: 1800
maxHp: 500
mass: 7800
techLevel: 3
buildSpeed: 5s
radius: 12
displayRadius: 12
isBio: false
availableInDemo: true
armour: 3
armourMinDamageToKeep: 2
displayText: A3-02 Wick
displayDescription: -flame walker

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.1

[graphics]
total_frames: 1
image: aeA3_02_Wick.png
image_wreak: aeA3_02_Wick_dead.png
image_turret: aeA3_02_Wick_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 9
turretTurnSpeed: 4
maxAttackRange: 150
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: firing3
shoot_sound_vol: 0.2

[projectile_1]
directDamage: 6
areaDamage: 4
areaRadius: 12
life: 25
speed: 7
speedSpread: 1
frame: 3
drawSize: 1.5

[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
