# R2-01 Hound - AE flame runner
[core]
name: ae_R2_01_Hound
class: CustomUnitMetadata
price: 800
maxHp: 160
mass: 2720
techLevel: 2
buildSpeed: 3s
radius: 10
displayRadius: 10
isBio: false
availableInDemo: true
displayText: R2-01 Hound
displayDescription: -flame runner

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.9

[graphics]
total_frames: 1
image: ae_R2_01_Hound.png
image_wreak: ae_R2_01_Hound_dead.png
image_turret: ae_R2_01_Hound_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 7
turretTurnSpeed: 4
maxAttackRange: 140
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: firing3
shoot_sound_vol: 0.2

[projectile_1]
directDamage: 4
areaDamage: 4
areaRadius: 12
life: 25
speed: 7
speedSpread: 1
frame: 3
drawSize: 1.5

[movement]
movementType: LAND
moveSpeed: 1.3
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
