# Axolotl - AE tracked healer
[core]
name: aeAxolotl
class: CustomUnitMetadata
price: 1100
maxHp: 260
mass: 4220
techLevel: 2
buildSpeed: 4s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
maxShield: 100
shieldRegen: 0.15
canRepairUnits: true
nanoRepairSpeed: 0.3
nanoRange: 85
displayText: Axolotl
displayDescription: -tracked healer

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.3

[graphics]
total_frames: 1
image: aeAxolotl.png
image_wreak: aeAxolotl_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
