# X5-08 Singularity - AE the final unit
[core]
name: ae_X5_08_Singularity
class: CustomUnitMetadata
price: 15000
maxHp: 2000
mass: 39000
techLevel: 3
buildSpeed: 15s
radius: 22
displayRadius: 22
isBio: false
availableInDemo: true
armour: 14
nukeOnDeath: true
nukeOnDeathRange: 150
nukeOnDeathDamage: 1200
armourMinDamageToKeep: 7
displayText: X5-08 Singularity
displayDescription: -the final unit

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 18.7

[graphics]
total_frames: 1
image: ae_X5_08_Singularity.png
image_wreak: ae_X5_08_Singularity_dead.png
image_turret: ae_X5_08_Singularity_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 19
turretTurnSpeed: 5
maxAttackRange: 230
shootDelay: 2.2s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 180
life: 70
speed: 6
frame: 4
drawSize: 1
shoot_sound: missile_fire
shoot_sound_vol: 0.2

[projectile_1]
directDamage: 30
life: 70
speed: 1.5
targetSpeed: 7
image: rocket.png
trailEffect: true

[turret_2]
x: -6
y: 5
attachedTo: 1
slave: true
invisible: true
projectile: 2
turnSpeed: 8
delay: 0.2s
limitingRange: 140
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: gun_fire
shoot_sound_vol: 0.1

[projectile_2]
directDamage: 8
life: 40
speed: 9
frame: 0
drawSize: 0.8

[turret_3]
x: 6
y: 5
attachedTo: 1
slave: true
invisible: true
projectile: 2
turnSpeed: 8
delay: 0.2s
limitingRange: 140
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: gun_fire
shoot_sound_vol: 0.1

[movement]
movementType: LAND
moveSpeed: 0.3
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
