# S3-09 Hearth - AE repair station
[core]
name: ae_S3_09_Hearth
class: CustomUnitMetadata
price: 1700
maxHp: 600
mass: 8900
techLevel: 3
buildSpeed: 5s
radius: 13
displayRadius: 13
isBio: false
availableInDemo: true
canRepairUnits: true
nanoRepairSpeed: 0.3
nanoRange: 85
displayText: S3-09 Hearth
displayDescription: -repair station

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.9

[graphics]
total_frames: 1
image: ae_S3_09_Hearth.png
image_wreak: ae_S3_09_Hearth_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: LAND
moveSpeed: 0.5
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
