# E4-07 Rail - AE mass driver
[core]
name: ae_E4_07_Rail
class: CustomUnitMetadata
price: 5000
maxHp: 300
mass: 8600
techLevel: 3
buildSpeed: 8s
radius: 13
displayRadius: 13
isBio: false
availableInDemo: true
displayText: E4-07 Rail
displayDescription: -mass driver

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 17.6

[graphics]
total_frames: 1
image: ae_E4_07_Rail.png
image_wreak: ae_E4_07_Rail_dead.png
image_turret: ae_E4_07_Rail_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 5
maxAttackRange: 4.0
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2
shoot_sound: plasma_fire2
shoot_sound_vol: 0.25

[projectile_1]
directDamage: 120
life: 25
instant: true
frame: 0
drawSize: 1.2

[movement]
movementType: LAND
moveSpeed: 0.4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
