# E4-03 Tesla - AE chain lightning tank
[core]
name: ae_E4_03_Tesla
class: CustomUnitMetadata
price: 3000
maxHp: 400
mass: 7800
techLevel: 3
buildSpeed: 6s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
displayText: E4-03 Tesla
displayDescription: -chain lightning tank

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 17.4

[graphics]
total_frames: 1
image: ae_E4_03_Tesla.png
image_wreak: ae_E4_03_Tesla_dead.png
image_turret: ae_E4_03_Tesla_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 5
maxAttackRange: 0.8
shootDelay: {'lightning': True}s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2
shoot_sound: lighting_burst
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:sparks2*3
shoot_light: #FFcceeee
chargeEffectImage: lighting_charge.png

[projectile_1]
directDamage: 90
life: 25
instant: true
lightingEffect: true
frame: 0
drawSize: 1.2

[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
