# Kestrel - AE multi-role missiles
[core]
name: aeKestrel
class: CustomUnitMetadata
price: 1500
maxHp: 200
mass: 3900
techLevel: 2
buildSpeed: 4s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
displayText: Kestrel
displayDescription: -multi-role missiles

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.7

[graphics]
total_frames: 1
image: aeKestrel.png
image_wreak: aeKestrel_dead.png
image_turret: aeKestrel_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 4
maxAttackRange: 200
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: missile_fire
shoot_sound_vol: 0.2

[projectile_1]
directDamage: 35
life: 70
speed: 1.5
targetSpeed: 7
image: rocket.png
trailEffect: true

[movement]
movementType: HOVER
moveSpeed: 1.1
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
