# R2-07 Ferry - AE amphibious transport
[core]
name: ae_R2_07_Ferry
class: CustomUnitMetadata
price: 800
maxHp: 280
mass: 4160
techLevel: 2
buildSpeed: 3s
radius: 12
displayRadius: 12
isBio: false
availableInDemo: true
fogOfWarSightRange: 24
maxTransportingUnits: 4
transportUnitsRequireMovementType: LAND, WATER
displayText: R2-07 Ferry
displayDescription: -amphibious transport

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.9

[graphics]
total_frames: 1
image: ae_R2_07_Ferry.png
image_wreak: ae_R2_07_Ferry_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 9
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: HOVER
moveSpeed: 0.9
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
