# H3-01 Lance - AE railgun sniper
[core]
name: ae_H3_01_Lance
class: CustomUnitMetadata
price: 2200
maxHp: 260
mass: 5320
techLevel: 3
buildSpeed: 5s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
displayText: H3-01 Lance
displayDescription: -railgun sniper

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.5

[graphics]
total_frames: 1
image: ae_H3_01_Lance.png
image_wreak: ae_H3_01_Lance_dead.png
image_turret: ae_H3_01_Lance_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 4
maxAttackRange: 1.5
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: plasma_fire2
shoot_sound_vol: 0.25

[projectile_1]
directDamage: 70
life: 25
instant: true
frame: 0
drawSize: 1.2

[movement]
movementType: LAND
moveSpeed: 0.8
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
