# H3-05 Scatter - AE cluster artillery
[core]
name: ae_H3_05_Scatter
class: CustomUnitMetadata
price: 2400
maxHp: 180
mass: 4560
techLevel: 3
buildSpeed: 6s
radius: 12
displayRadius: 12
isBio: false
availableInDemo: true
displayText: H3-05 Scatter
displayDescription: -cluster artillery

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.7

[graphics]
total_frames: 1
image: ae_H3_05_Scatter.png
image_wreak: ae_H3_05_Scatter_dead.png
image_turret: ae_H3_05_Scatter_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 9
turretTurnSpeed: 4
maxAttackRange: 300
shootDelay: {'shrapnel': 6}s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: cannon_firing
shoot_sound_vol: 0.3

[projectile_1]
directDamage: 15
areaDamage: 50
areaRadius: 35
life: 90
speed: 4
ballistic: true
ballistic_height: 30
frame: 3
drawSize: 1
trailEffect: true
spawnProjectilesOnEndOfLife: shrap*6(offsetRandomXY=25)

[projectile_shrap]
directDamage: 10
life: 25
speed: 3
frame: 1
drawSize: 0.7

[movement]
movementType: LAND
moveSpeed: 0.55
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
