# Hailstorm - AE heavy AA
[core]
name: aeHailstorm
class: CustomUnitMetadata
price: 3200
maxHp: 400
mass: 8000
techLevel: 3
buildSpeed: 7s
radius: 12
displayRadius: 12
isBio: false
availableInDemo: true
displayText: Hailstorm
displayDescription: -heavy AA

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.6

[graphics]
total_frames: 1
image: aeHailstorm.png
image_wreak: aeHailstorm_dead.png
image_turret: aeHailstorm_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 9
turretTurnSpeed: 4
maxAttackRange: 260
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: missile_fire
shoot_sound_vol: 0.2

[projectile_1]
directDamage: 40
life: 70
speed: 1.5
targetSpeed: 7
image: rocket.png
trailEffect: true

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
