# X5-03 Bastion - AE shield citadel
[core]
name: ae_X5_03_Bastion
class: CustomUnitMetadata
price: 8000
maxHp: 1200
mass: 22400
techLevel: 3
buildSpeed: 11s
radius: 16
displayRadius: 16
isBio: false
availableInDemo: true
maxShield: 600
shieldRegen: 0.15
canRepairUnits: true
nanoRepairSpeed: 0.3
nanoRange: 85
displayText: X5-03 Bastion
displayDescription: -shield citadel

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 18.9

[graphics]
total_frames: 1
image: ae_X5_03_Bastion.png
image_wreak: ae_X5_03_Bastion_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 13
turretTurnSpeed: 5
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: LAND
moveSpeed: 0.3
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
