# Mine - AE proximity mine
[core]
name: aeMine
class: CustomUnitMetadata
price: 0
maxHp: 25
mass: 300
techLevel: 2
buildSpeed: 2s
radius: 5
displayRadius: 5
isBio: false
availableInDemo: true
displayText: Mine
displayDescription: -proximity mine


[graphics]
total_frames: 1
image: aeMine.png
image_wreak: aeMine_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColoringMode: pureGreen

[attack]
isMelee: true
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 5
turretTurnSpeed: 4
maxAttackRange: 10
shootDelay: 0.5s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2

[projectile_1]
directDamage: 300
life: 10
speed: 5
frame: 0
drawSize: 0.5

[movement]
movementType: HOVER
moveSpeed: 0.0
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 5
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
