# X5-02 Storm - AE lightning fortress
[core]
name: ae_X5_02_Storm
class: CustomUnitMetadata
price: 7000
maxHp: 600
mass: 14200
techLevel: 3
buildSpeed: 10s
radius: 16
displayRadius: 16
isBio: false
availableInDemo: true
armour: 6
armourMinDamageToKeep: 3
displayText: X5-02 Storm
displayDescription: -lightning fortress

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 18.8

[graphics]
total_frames: 1
image: ae_X5_02_Storm.png
image_wreak: ae_X5_02_Storm_dead.png
image_turret: ae_X5_02_Storm_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 13
turretTurnSpeed: 5
maxAttackRange: 0.6
shootDelay: {'lightning': True, 'multi': 4}s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2
shoot_sound: lighting_burst
shoot_sound_vol: 0.3
shoot_flame: CUSTOM:sparks2*3
shoot_light: #FFcceeee
chargeEffectImage: lighting_charge.png

[projectile_1]
directDamage: 70
life: 25
instant: true
lightingEffect: true
frame: 0
drawSize: 1.2

[movement]
movementType: LAND
moveSpeed: 0.45
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
