# H3-07 Needle - AE beam sniper
[core]
name: ae_H3_07_Needle
class: CustomUnitMetadata
price: 2600
maxHp: 240
mass: 5480
techLevel: 3
buildSpeed: 6s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
displayText: H3-07 Needle
displayDescription: -beam sniper

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.9

[graphics]
total_frames: 1
image: ae_H3_07_Needle.png
image_wreak: ae_H3_07_Needle_dead.png
image_turret: ae_H3_07_Needle_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 4
maxAttackRange: 1.6
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: plasma_fire2
shoot_sound_vol: 0.25

[projectile_1]
directDamage: 90
life: 25
instant: true
frame: 0
drawSize: 1.2

[movement]
movementType: LAND
moveSpeed: 0.75
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
