# D2-09 Ricochet - AE dodge skirmisher
[core]
name: ae_D2_09_Ricochet
class: CustomUnitMetadata
price: 600
maxHp: 110
mass: 1920
techLevel: 2
buildSpeed: 3s
radius: 9
displayRadius: 9
isBio: false
availableInDemo: true
maxShield: 80
shieldRegen: 0.15
displayText: D2-09 Ricochet
displayDescription: -dodge skirmisher

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.7

[graphics]
total_frames: 1
image: ae_D2_09_Ricochet.png
image_wreak: ae_D2_09_Ricochet_dead.png
image_turret: ae_D2_09_Ricochet_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 6
turretTurnSpeed: 4
maxAttackRange: 100
shootDelay: 0.6s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: tank_firing
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 12
life: 70
speed: 6
frame: 2
drawSize: 1

[movement]
movementType: LAND
moveSpeed: 1.6
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
