# S3-04 Puffer - AE shield-bus healer
[core]
name: ae_S3_04_Puffer
class: CustomUnitMetadata
price: 1600
maxHp: 350
mass: 5800
techLevel: 3
buildSpeed: 5s
radius: 12
displayRadius: 12
isBio: false
availableInDemo: true
maxShield: 250
shieldRegen: 0.15
canRepairUnits: true
nanoRepairSpeed: 0.3
nanoRange: 85
displayText: S3-04 Puffer
displayDescription: -shield-bus healer

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.8

[graphics]
total_frames: 1
image: ae_S3_04_Puffer.png
image_wreak: ae_S3_04_Puffer_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 9
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
