# Mantis - AE tank hunter
[core]
name: aeMantis
class: CustomUnitMetadata
price: 1300
maxHp: 260
mass: 4420
techLevel: 2
buildSpeed: 4s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
displayText: Mantis
displayDescription: -tank hunter

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.5

[graphics]
total_frames: 1
image: aeMantis.png
image_wreak: aeMantis_dead.png
image_turret: aeMantis_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 4
maxAttackRange: 170
shootDelay: 1.8s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: missile_fire
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 90
life: 70
speed: 6
frame: 6
drawSize: 1

[movement]
movementType: LAND
moveSpeed: 1.0
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
