# R3-06 Newt - AE amphibious scout
[core]
name: ae_R3_06_Newt
class: CustomUnitMetadata
price: 400
maxHp: 140
mass: 2080
techLevel: 3
buildSpeed: 2s
radius: 8
displayRadius: 8
isBio: false
availableInDemo: true
fogOfWarSightRange: 36
displayText: R3-06 Newt
displayDescription: -amphibious scout

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.5

[graphics]
total_frames: 1
image: ae_R3_06_Newt.png
image_wreak: ae_R3_06_Newt_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColoringMode: pureGreen

[attack]
canAttack: false
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false
turretSize: 5
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25


[movement]
movementType: HOVER
moveSpeed: 1.9
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 4
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
