# X5-01 Omega - AE omega tank
[core]
name: ae_X5_01_Omega
class: CustomUnitMetadata
price: 9000
maxHp: 1800
mass: 30600
techLevel: 3
buildSpeed: 11s
radius: 18
displayRadius: 18
isBio: false
availableInDemo: true
armour: 12
armourMinDamageToKeep: 6
displayText: X5-01 Omega
displayDescription: -omega tank

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 18.1

[graphics]
total_frames: 1
image: ae_X5_01_Omega.png
image_wreak: ae_X5_01_Omega_dead.png
image_turret: ae_X5_01_Omega_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 15
turretTurnSpeed: 5
maxAttackRange: 200
shootDelay: 2.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 120
life: 70
speed: 6
frame: 4
drawSize: 1

[turret_2]
x: -6
y: 5
attachedTo: 1
slave: true
invisible: true
projectile: 2
turnSpeed: 8
delay: 0.2s
limitingRange: 140
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: gun_fire
shoot_sound_vol: 0.1

[projectile_2]
directDamage: 8
life: 40
speed: 9
frame: 0
drawSize: 0.8

[turret_3]
x: 6
y: 5
attachedTo: 1
slave: true
invisible: true
projectile: 2
turnSpeed: 8
delay: 0.2s
limitingRange: 140
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: gun_fire
shoot_sound_vol: 0.1

[movement]
movementType: LAND
moveSpeed: 0.55
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
