# E4-08 Leech - AE vampiric crawler
[core]
name: ae_E4_08_Leech
class: CustomUnitMetadata
price: 2800
maxHp: 500
mass: 8800
techLevel: 3
buildSpeed: 6s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
selfRegenRate: 0.25
displayText: E4-08 Leech
displayDescription: -vampiric crawler

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 17.2

[graphics]
total_frames: 1
image: ae_E4_08_Leech.png
image_wreak: ae_E4_08_Leech_dead.png
image_turret: ae_E4_08_Leech_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 5
maxAttackRange: 140
shootDelay: 0.9s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2
shoot_sound: tank_firing
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 35
life: 70
speed: 6
frame: 4
drawSize: 1

[movement]
movementType: LAND
moveSpeed: 0.7
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
