# D3-03 Horn - AE counter-battery
[core]
name: ae_D3_03_Horn
class: CustomUnitMetadata
price: 2000
maxHp: 220
mass: 4640
techLevel: 3
buildSpeed: 5s
radius: 11
displayRadius: 11
isBio: false
availableInDemo: true
displayText: D3-03 Horn
displayDescription: -counter-battery

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.3

[graphics]
total_frames: 1
image: ae_D3_03_Horn.png
image_wreak: ae_D3_03_Horn_dead.png
image_turret: ae_D3_03_Horn_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 8
turretTurnSpeed: 4
maxAttackRange: 380
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: cannon_firing
shoot_sound_vol: 0.3

[projectile_1]
directDamage: 15
areaDamage: 45
areaRadius: 25
life: 90
speed: 4
ballistic: true
ballistic_height: 30
frame: 3
drawSize: 1
trailEffect: true

[movement]
movementType: LAND
moveSpeed: 0.55
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
