# D3-08 Hedgehog - AE AA walker
[core]
name: ae_D3_08_Hedgehog
class: CustomUnitMetadata
price: 2300
maxHp: 520
mass: 8540
techLevel: 3
buildSpeed: 5s
radius: 12
displayRadius: 12
isBio: false
availableInDemo: true
armour: 4
armourMinDamageToKeep: 2
displayText: D3-08 Hedgehog
displayDescription: -AA walker

builtFrom_1_name: landFactory
builtFrom_1_pos: 16.6

[graphics]
total_frames: 1
image: ae_D3_08_Hedgehog.png
image_wreak: ae_D3_08_Hedgehog_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 9
turretTurnSpeed: 4
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2

[movement]
movementType: LAND
moveSpeed: 0.65
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
