# H2-04 Skate - AE hover missile cart
[core]
name: ae_H2_04_Skate
class: CustomUnitMetadata
price: 1000
maxHp: 140
mass: 2680
techLevel: 2
buildSpeed: 3s
radius: 10
displayRadius: 10
isBio: false
availableInDemo: true
maxShield: 40
shieldRegen: 0.15
displayText: H2-04 Skate
displayDescription: -hover missile cart

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.2

[graphics]
total_frames: 1
image: ae_H2_04_Skate.png
image_wreak: ae_H2_04_Skate_dead.png
image_turret: ae_H2_04_Skate_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 7
turretTurnSpeed: 4
maxAttackRange: 160
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: missile_fire
shoot_sound_vol: 0.2

[projectile_1]
directDamage: 20
life: 70
speed: 1.5
targetSpeed: 7
image: rocket.png
trailEffect: true

[movement]
movementType: HOVER
moveSpeed: 1.4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
