# E4-04 Doomsday - AE nuke launcher
[core]
name: ae_E4_04_Doomsday
class: CustomUnitMetadata
price: 8000
maxHp: 500
mass: 14000
techLevel: 3
buildSpeed: 11s
radius: 18
displayRadius: 18
isBio: false
availableInDemo: true
displayText: E4-04 Doomsday
displayDescription: -nuke launcher

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 17.9

[graphics]
total_frames: 1
image: ae_E4_04_Doomsday.png
image_wreak: ae_E4_04_Doomsday_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 15
turretTurnSpeed: 5
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2

[turret_silo]
x: 0
y: 0
canShoot: false

[turret_siloTop]
attachedTo: silo
slave: true
invisible: true
projectile: nukeProjectile
shoot_sound: nuke_launch
shoot_sound_vol: 0.5
shoot_flame: CUSTOM:sparks2*3, CUSTOM:lightSlowFade

[projectile_nukeProjectile]
tags: nuke
directDamage: 120
life: 99999
speed: 0.1
targetSpeed: 2.7
targetSpeedAcceleration: 0.02
largeHitEffect: true
ballistic: true
ballistic_delaymove_height: 80
ballistic_height: 110
frame: 0
drawType: 1
targetGround: true
areaDamage: 5000
areaHitAirAndLandAtSameTime: true
alwaysVisibleInFog: true
areaRadius: 220
areaExpandTime: 75
shouldRevealFog: true
nukeWeapon: true

[effect_lightSlowFade]
image: light_50.png
life: 40
fadeOut: true
attachedToUnit: true
color: #ffddaa
scaleFrom: 0.7
scaleTo: 0.7
alpha: 0.5
drawUnderUnits: true

[movement]
movementType: LAND
moveSpeed: 0
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
