# Ankylo - AE heavy tank
[core]
name: aeAnkylo
class: CustomUnitMetadata
price: 1400
maxHp: 700
mass: 9800
techLevel: 2
buildSpeed: 4s
radius: 13
displayRadius: 13
isBio: false
availableInDemo: true
armour: 4
armourMinDamageToKeep: 2
displayText: Ankylo
displayDescription: -heavy tank

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.6

[graphics]
total_frames: 1
image: aeAnkylo.png
image_wreak: aeAnkylo_dead.png
image_turret: aeAnkylo_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 10
turretTurnSpeed: 4
maxAttackRange: 150
shootDelay: 1.6s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: large_gun_fire1
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 55
life: 70
speed: 6
frame: 4
drawSize: 1

[movement]
movementType: LAND
moveSpeed: 0.6
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
