# A2-02 Viper - AE mine layer
[core]
name: ae_A2_02_Viper
class: CustomUnitMetadata
price: 900
maxHp: 200
mass: 3300
techLevel: 2
buildSpeed: 3s
radius: 10
displayRadius: 10
isBio: false
availableInDemo: true
displayText: A2-02 Viper
displayDescription: -mine layer

builtFrom_1_name: landFactory
builtFrom_1_pos: 15.1

[graphics]
total_frames: 1
image: ae_A2_02_Viper.png
image_wreak: ae_A2_02_Viper_dead.png
image_turret: ae_A2_02_Viper_turret.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 7
turretTurnSpeed: 4
maxAttackRange: 90
shootDelay: 0.5s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 4
recoilOffset: -2
shoot_sound: gun_fire
shoot_sound_vol: 0.25
shoot_flame: small
shoot_light: #FFEECCCC

[projectile_1]
directDamage: 10
life: 70
speed: 6
frame: 2
drawSize: 1

[action_layMine]
text: Lay Mine
buildSpeed: 2s
pos: 1
spawnUnits: aeMine(offsetRandomXY=40, spawnChance=1)
addActionCooldownTime: 4s
displayType: action

[movement]
movementType: LAND
moveSpeed: 1.1
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 3
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: false
