# X5-06 Hive - AE mothership crawler
[core]
name: ae_X5_06_Hive
class: CustomUnitMetadata
price: 9500
maxHp: 1000
mass: 21500
techLevel: 3
buildSpeed: 12s
radius: 17
displayRadius: 17
isBio: false
availableInDemo: true
maxTransportingUnits: 6
isBuilder: true
nanoBuildSpeed: 2
canRepairUnits: true
nanoRepairSpeed: 0.3
nanoRange: 85
transportUnitsRequireMovementType: LAND
displayText: X5-06 Hive
displayDescription: -mothership crawler

builtFrom_1_name: aeExperimentalFactory
builtFrom_1_pos: 18.6

[canBuild_1]
name: aeHornet
pos: 1
forceNano: true

[canBuild_2]
name: aeThorn
pos: 2
forceNano: true

[graphics]
total_frames: 1
image: ae_X5_06_Hive.png
image_wreak: ae_X5_06_Hive_dead.png
image_turret: NONE
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColoringMode: pureGreen

[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
turretSize: 14
turretTurnSpeed: 5
maxAttackRange: 0
shootDelay: 1.0s
aimOffsetSpread: 0.25

[turret_1]
x: 0
y: 0
projectile: 1
canShoot: true
turnSpeed: 5
recoilOffset: -2

[turret_2]
x: -6
y: 5
attachedTo: 1
slave: true
invisible: true
projectile: 2
turnSpeed: 8
delay: 0.2s
limitingRange: 140
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: gun_fire
shoot_sound_vol: 0.1

[projectile_2]
directDamage: 8
life: 40
speed: 9
frame: 0
drawSize: 0.8

[turret_3]
x: 6
y: 5
attachedTo: 1
slave: true
invisible: true
projectile: 2
turnSpeed: 8
delay: 0.2s
limitingRange: 140
canAttackFlyingUnits: true
canAttackLandUnits: true
canAttackUnderwaterUnits: false
shoot_sound: gun_fire
shoot_sound_vol: 0.1

[movement]
movementType: LAND
moveSpeed: 0.4
moveAccelerationSpeed: 0.06
moveDecelerationSpeed: 0.15
maxTurnSpeed: 2
turnAcceleration: 0.25
moveSlidingMode: false
moveIgnoringBody: false

[ai]
useAsBuilder: true
